owner: "6526960"
team: null
lastUpdatedBy: "6526960"
lastRevision: 1761299459000
name: Development
color: null
values:
  - key: X-API-Token
    value: testing
    enabled: true
  - key: basse_url
    value: ""
    enabled: true
createdAt: 2025-06-20T12:04:05.000Z
updatedAt: 2025-10-24T09:50:59.000Z
